defaults: &defaults
 
:development:
  :couchdb:
    :url: http://localhost:5984/samwarmuth_development
  <<: *defaults
  
:test:
  :couchdb:
    :url: http://localhost:5984/samwarmuth_test
    <<: *defaults

:production:
  :couchdb:
    :url: http://localhost:5984/samwarmuth_prod
    <<: *defaults